CREATE DATABASE IF NOT EXISTS logiware;
USE logiware;

CREATE TABLE IF NOT EXISTS admin_users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(80) UNIQUE NOT NULL,
  password_hash VARCHAR(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  category VARCHAR(80) NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  weight DECIMAL(10,2) NOT NULL,
  reorderLevel INT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS warehouses (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  location VARCHAR(160) NOT NULL,
  capacity INT NOT NULL,
  storageType VARCHAR(80) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS suppliers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  contactPerson VARCHAR(120),
  email VARCHAR(120),
  phone VARCHAR(40),
  address VARCHAR(220),
  creditLimit DECIMAL(12,2) NOT NULL DEFAULT 0,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS inventory (
  id INT AUTO_INCREMENT PRIMARY KEY,
  productId INT NOT NULL,
  warehouseId INT NOT NULL,
  quantity INT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS purchase_orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  supplierId INT NOT NULL,
  productId INT NOT NULL,
  quantity INT NOT NULL,
  status VARCHAR(40) NOT NULL,
  expectedDate VARCHAR(40),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS shipments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  orderId INT,
  trackingNumber VARCHAR(120),
  carrier VARCHAR(120),
  status VARCHAR(40) NOT NULL,
  origin VARCHAR(160),
  destination VARCHAR(160),
  shipDate VARCHAR(40),
  deliveryDate VARCHAR(40),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS product_returns (
  id INT AUTO_INCREMENT PRIMARY KEY,
  productId INT NOT NULL,
  shipmentId INT,
  quantity INT NOT NULL,
  reason VARCHAR(220),
  status VARCHAR(40) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS payments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  supplierId INT NOT NULL,
  orderId INT,
  amount DECIMAL(12,2) NOT NULL,
  paymentDate VARCHAR(40) NOT NULL,
  method VARCHAR(60) NOT NULL,
  status VARCHAR(40) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS supplier_ledger (
  id INT AUTO_INCREMENT PRIMARY KEY,
  supplierId INT NOT NULL,
  entryType VARCHAR(40) NOT NULL,
  referenceId INT,
  debit DECIMAL(12,2) NOT NULL DEFAULT 0,
  credit DECIMAL(12,2) NOT NULL DEFAULT 0,
  entryDate VARCHAR(40) NOT NULL,
  note VARCHAR(220),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS invoices (
  id INT AUTO_INCREMENT PRIMARY KEY,
  orderId INT NOT NULL UNIQUE,
  orderCost DECIMAL(12,2) NOT NULL,
  taxAmount DECIMAL(12,2) NOT NULL,
  totalAmount DECIMAL(12,2) NOT NULL,
  invoiceDate VARCHAR(40) NOT NULL,
  status VARCHAR(40) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS product_batches (
  id INT AUTO_INCREMENT PRIMARY KEY,
  batchCode VARCHAR(80) NOT NULL UNIQUE,
  productId INT NOT NULL,
  supplierId INT NOT NULL,
  quantity INT NOT NULL,
  receivedDate VARCHAR(40) NOT NULL,
  expiryDate VARCHAR(40),
  status VARCHAR(40) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
