CREATE DATABASE IF NOT EXISTS logiware;
USE logiware;

CREATE TABLE IF NOT EXISTS admin_users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(80) UNIQUE NOT NULL,
  password_hash VARCHAR(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  category VARCHAR(80) NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  weight DECIMAL(10,2) NOT NULL,
  reorderLevel INT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS warehouses (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  location VARCHAR(160) NOT NULL,
  capacity INT NOT NULL,
  storageType VARCHAR(80) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS suppliers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  contactPerson VARCHAR(120),
  email VARCHAR(120),
  phone VARCHAR(40),
  address VARCHAR(220),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS inventory (
  id INT AUTO_INCREMENT PRIMARY KEY,
  productId INT NOT NULL,
  warehouseId INT NOT NULL,
  quantity INT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS purchase_orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  supplierId INT NOT NULL,
  productId INT NOT NULL,
  quantity INT NOT NULL,
  status VARCHAR(40) NOT NULL,
  expectedDate VARCHAR(40),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS shipments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  orderId INT,
  trackingNumber VARCHAR(120),
  carrier VARCHAR(120),
  status VARCHAR(40) NOT NULL,
  origin VARCHAR(160),
  destination VARCHAR(160),
  shipDate VARCHAR(40),
  deliveryDate VARCHAR(40),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS product_returns (
  id INT AUTO_INCREMENT PRIMARY KEY,
  productId INT NOT NULL,
  shipmentId INT,
  quantity INT NOT NULL,
  reason VARCHAR(220),
  status VARCHAR(40) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
